# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Bitwarden Secrets for ${BUILD_ARCH}"
  org.opencontainers.image.description: "Home Assistant Unofficial Add-on: ${BUILD_ARCH} Bitwarden secrets for Home Assistant image."
  org.opencontainers.image.source: "https://alxx.nl/home-assistant-addons/"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
